Repository pascal-zarrad/psh, pull requests merged in 2019-10, with the labels that each got.

#2 Add TravisCI
  .travis.yml
  README.MD
  fix-wsl.sh
  install.sh
Labels: enhancement

#3 Add build status badge
  README.MD
Labels: documentation

#4 Fix code style
  .gitattributes
  install.sh
Labels: enhancement

#5 Add additional zsh plugins
  README.MD
  plugins/auto-suggestions/plugin.sh
  plugins/command-not-found/plugin.sh
  plugins/docker/plugin.sh
  plugins/git/plugin.sh
  plugins/node/plugin.sh
  plugins/php/plugin.sh
  plugins/pip/plugin.sh
  plugins/python/plugin.sh
  plugins/rsync/plugin.sh
  plugins/syntax-highlighting/plugin.sh
  plugins/yarn/plugin.sh
  plugins/zsh-enhancements/plugin.sh
Labels: enhancement

#9 Add pull request template and contributing guide
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.MD
Labels: documentation

#10 Fix missing word
  README.MD
Labels: documentation

#11 Further improve code quality
  install.sh
Labels: enhancement

#12 Implement template system
  README.MD
  install.sh
  templates/psh_alias.template.zshrc
Labels: enhancement

#13 Fix constant typo
  README.MD
  install.sh
Labels: enhancement

#14 Update docs
  README.MD
Labels: documentation

#24 Feature/improve template engine
  install.sh
  lib/template_engine.sh
Labels: enhancement

#25 Fix theme-loader on WSL2
  README.MD
  plugins/theme-loader/plugin.sh
Labels: bug

#26 Execute apt update & upgrade on dependency installation
  install.sh
  lib/template_engine.sh
Labels: bug

#27 Only include files with proper extension
  lib/template_engine.sh
Labels: enhancement

#28 Add a write function to plugin api
  install.sh
  lib/plugin_api.sh
Labels: enhancement

#29 Feature/prevent template inclusion
  install.sh
  lib/template_engine.sh
Labels: enhancement

#30 Add argument to disable plugin execution
  install.sh
Labels: enhancement

#32 Remove apt upgrade
  install.sh
Labels: bug

#33 Add option of unattended installation
  install.sh
Labels: enhancement
